-- Table 삭제
DROP TABLE TRADE;
DROP TABLE ACCOUNT;
DROP TABLE MEMBER;
DROP TABLE BANKBOOK;

SELECT * FROM TAB;
SELECT * FROM USER_CONSTRAINTS;

DROP VIEW EMP_DETAILS_VIEW;
DROP TABLE JOB_HISTORY;
DROP TABLE JOBS;

-- Employees에서 manager_id 외래키 삭제
ALTER TABLE EMPLOYEES DROP CONSTRAINT EMP_MANAGER_FK;
-- Departments에서 manager_id 외래키 삭제
ALTER TABLE DEPARTMENTS DROP CONSTRAINT DEPT_MGR_FK;
-- Employees 삭제
DROP TABLE EMPLOYEES;
-- Departments 삭제
DROP TABLE DEPARTMENTS;
-- Locations 삭제
DROP TABLE LOCATIONS;
-- Countries 삭제
DROP TABLE COUNTRIES;
-- Regions 삭제
DROP TABLE REGIONS;

-- SEQ 확인, 삭제
SELECT * FROM SEQ;
DROP SEQUENCE BOARD_SEQ;
DROP SEQUENCE CART_SEQ;
DROP SEQUENCE DEPARTMENTS_SEQ;
DROP SEQUENCE EMPLOYEES_SEQ;
DROP SEQUENCE LOCATIONS_SEQ;
DROP SEQUENCE PRODUCT_SEQ;

-- BANKBOOK TABLE 생성
CREATE TABLE BANKBOOK (
    BOOKNUMBER NUMBER CONSTRAINT BB_BN_PK PRIMARY KEY,
    BOOKNAME VARCHAR2(100),
    BOOKCONTENTS VARCHAR2(4000),
    BOOKRATE NUMBER(3, 2),
    BOOKSALE NUMBER(1)
);

CREATE SEQUENCE BANKBOOK_SEQ
    INCREMENT BY 1
    START WITH 1;

SELECT * FROM BANKBOOK;

INSERT INTO BANKBOOK(booknumber, bookname, bookcontents, bookrate, booksale)
VALUES (BANKBOOK_SEQ.nextval, 't1', 'c1', 3.2, 0);

SELECT * FROM BANKBOOK WHERE BOOKNUMBER = 3;

DELETE BANKBOOK WHERE BOOKNUMBER = 3;

-- NOTICE TABLE 생성
CREATE TABLE NOTICE (
    NOTICENUM NUMBER CONSTRAINT NO_NUM_PK PRIMARY KEY,
    NOTICETITLE VARCHAR2(1000),
    NOTICECONTENTS VARCHAR2(4000),
    NOTICEWRITER VARCHAR2(1000),
    NOTICEREGDATE DATE,
    NOTICEHIT NUMBER
);

SELECT * FROM notice;

-- NOTICE SEQ 생성
CREATE SEQUENCE NOTICE_SEQ
    INCREMENT BY 1
    START WITH 1;
    

COMMIT;