-- ABS

SELECT ABS(-10) FROM DUAL;

-- FLOOR
SELECT FLOOR(12.34) FROM DUAL;

SELECT ROUND(17.45, -1) FROM DUAL;

SELECT TRUNC(12.55, -1) FROM DUAL;

SELECT MOD (9, 2) FROM DUAL;

SELECT LENGTH('한글') FROM DUAL;
SELECT LENGTHB('가글') FROM DUAL;

SELECT RPAD('111', 10, '#') FROM DUAL;
-- ABCDEF
SELECT RPAD(SUBSTR(FIRST_NAME, 1, 1), LENGTH(FIRST_NAME),'#') FROM EMPLOYEES;

SELECT RPAD(SUBSTR(MEMBER_ID,1,1),LENGTH(MEMBER_ID),'#') FROM MEMBER;
-- M######

SELECT SYSDATE, SYSDATE+1 FROM DUAL;

SELECT NEXT_DAY(SYSDATE, '일요일') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'YYYY,MM,DD') FROM DUAL;
SELECT TO_CHAR(30000000, '999,999,999') FROM DUAL;

SELECT TO_NUMBER('123')*2 FROM DUAL;
SELECT TO_NUMBER('1,222', '9,999') FROM DUAL;

-- 날짜형식 YYYY-MM-DD
SELECT TO_DATE('20211224', 'YYYY-MM-DD') FROM DUAL;
SELECT TO_DATE('21211224 153022', 'YYYY-MM-DD HH24:MI:SS') FROM DUAL;
